---
apiVersion: v1
kind: Service
metadata:
  name: po-lin-expensy-frontend
spec:
  type: NodePort
  selector:
    app: expensy-frontend
  ports:
    - port: 3000
      nodePort: 30001
      targetPort: 3000
