---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-lin-expensy-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensy-frontend
  template:
    metadata:
      labels:
        app: expensy-frontend
    spec:
      containers:
      - name: po-lin-expensy-frontend
        image: barberry/ironhack-expensy-frontend
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "/api"
